name: Pass checks and tests

on: [pull_request]
    
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"
  
    - name: Sync the depdendencies
      run: |
        eval `ssh-agent -s`
        ssh-add - <<< '${{ secrets.SSH_KEY }}'
        uv sync --all-extras --dev

    - name: Run tests
      run: uv run pytest tests/main.py

    - name: Ruff check
      run: uv run ruff check
